In [1]:
import pandas as pd
import numpy as np
import pickle

In [2]:
#面倒な前処理部分は今回エクセル上で実施済み
#別途前処理をするコードが必要
#

<b>--------------------国勢調査ー読み込みー開始-------------------------<b/>

In [3]:
#国勢調査
kokusei = pd.read_csv("/Users/01017387/Desktop/しごと/data/car用/加工済み/kokuseichosa_2015_for_merge.csv")
#全てを英字変換する必要あり
kokusei.columns=["pref_code", "pref_city_code", "capital_city_flg", "city_categories", "chiho", "city_name",
                 "population", "h22_kumikae_population", "population_changed_from_h22_to_h27", "rate_population_changed_from_h22_to_h27",
                 "gross_area", "population_density", "ave_age_from_h22_to_h27", "med_age_from_h22_to_h27", "population",
                 "population_under_15old", "population_from_15_to_64_old", "population_over_65old", "rate_population_under_15_year_old",
                 "rate_population_from_15_to_64_old", "rate_population_over_65old", "population_male","population_male_under_15old",
                 "population_male_from_15_to_64_old", "population_male_over_65old", "rate_population_male_under_15old",
                 "rate_population_male_from_15_to_64_old", "rate_population_male_over_65old", "population_female",
                 "population_female_under_15old", "population_female_from_15_to_64_old", "population_female_over_65old",
                 "rate_population_female_under_15old", "rate_population_female_from_15_to_64_old", "rate_population_female_over_65old",
                 "rate_population_male_to female", "population_jap", "population_no_jap", "num_of_family", "num_of_normal_family",
                 "num_of_family_in_facilities", "h22_kumikae_family", "num_of_normal_family", "num_of_nuclear_family",
                 "num_of_family_no_children", "num_of_family_with_children", "num_of_father_and_children", "num_of_mother_and_children",
                 "num_of_singles", "num_of_over_65old_singles", "num_of_old_married_couples_no_children", "num_of_3generation_family",]
# kokusei.columns
# print(kokusei.shape)
# kokusei.head()

In [4]:
#保有台数
hoyu = pd.read_csv("/Users/01017387/Desktop/しごと/data/car用/加工済み/2015_hoyu_daisu.csv",encoding="utf-8")
print(hoyu.columns)
hoyu.columns = ["chiho", "num_of_cars_all", "num_of_cars_kei", "num_of_cars_normal", "num_of_familiy", "cars_per_person",
                "normal_cars_per_person", "kei_cars_per_person", "kei_rate", "normal_rate", "kei_share_in_JP", "normal_share_in_JP",
                "guess_2nd_hand_kei_car_sales_per_year", "guess_2nd_hand_normal_car_sales_per_year", "guess_2nd_hand_car_all_sales_per_year"]
print(hoyu.shape)
hoyu.head()

Index(['都道府県名', '乗用車', '軽', '普通', '世帯数', '車両数/世帯数', '普通車両数/世帯数', '軽車両数/世帯数',
       '軽率', '普通率', '軽シェア', '普通シェア', '軽シェア×中古販売数', '普通シェア×中古販売数', '中古車販売台数'],
      dtype='object')
(47, 15)

,chiho,num_of_cars_all,num_of_cars_kei,num_of_cars_normal,num_of_familiy,cars_per_person,normal_cars_per_person,kei_cars_per_person,kei_rate,normal_rate,kei_share_in_JP,normal_share_in_JP,guess_2nd_hand_kei_car_sales_per_year,guess_2nd_hand_normal_car_sales_per_year,guess_2nd_hand_car_all_sales_per_year
0,北海道,"2,805,265",1142062,"1,663,203","2,734,906",1.025726,0.608139,0.417587,40.71%,59.29%,3.77%,5.39%,"37,693","161,743","199,436"
1,青森,"728,253",455493,"272,760","586,148",1.242439,0.465343,0.777096,62.55%,37.45%,1.50%,0.88%,"15,033","26,525","41,559"
2,岩手,"738,199",458943,"279,256","517,845",1.425521,0.539266,0.886256,62.17%,37.83%,1.51%,0.91%,"15,147","27,157","42,304"
3,宮城,"1,282,869",617560,"665,309","961,574",1.334134,0.691896,0.642239,48.14%,51.86%,2.04%,2.16%,"20,382","64,700","85,082"
4,秋田,"594,158",374063,"220,095","424,208",1.400629,0.518837,0.881791,62.96%,37.04%,1.23%,0.71%,"12,346","21,404","33,749"

In [5]:
#保有台数のキーの変更
# hoyu.rename(columns={"県名":"都道府県名"})
hoyu.head(2)
# hoyu["県名"]
#国勢調査と保有台数のマージ
koku_hoyu = pd.merge(kokusei,hoyu,on="chiho",how="left")
koku_hoyu = koku_hoyu.dropna(subset=['pref_code'])
print(koku_hoyu.shape)
koku_hoyu.tail(5)
#一番下に謎の欠損行が存在するので削除する

#OK

(1912, 66)

,pref_code,pref_city_code,capital_city_flg,city_categories,chiho,city_name,population,h22_kumikae_population,population_changed_from_h22_to_h27,rate_population_changed_from_h22_to_h27,...,cars_per_person,normal_cars_per_person,kei_cars_per_person,kei_rate,normal_rate,kei_share_in_JP,normal_share_in_JP,guess_2nd_hand_kei_car_sales_per_year,guess_2nd_hand_normal_car_sales_per_year,guess_2nd_hand_car_all_sales_per_year
1907,47.0,47361.0,NaN,3.0,沖縄県,久米島町,"7,755","8,519",-764,-9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1908,47.0,47362.0,NaN,3.0,沖縄県,八重瀬町,"29,066","26,681","2,385",8.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1909,47.0,47375.0,NaN,3.0,沖縄県,多良間村,"1,194","1,231",-37,-3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1910,47.0,47381.0,NaN,3.0,沖縄県,竹富町,"3,998","3,859",139,3.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1911,47.0,47382.0,NaN,3.0,沖縄県,与那国町,"1,843","1,657",186,11.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<b>
-----------------------国勢調査と保有台数のマージー終わり-----------------------<br>
-----------------------保有車両数マージー始まり-----------------------
<b/>

<b>
-----------------------保有車両数マージー終わり-----------------------<br>
-----------------------問い合わせ件数処理ー始まり-----------------------<br>
<b/>

In [6]:
#pickle形式でdataframeを保存
#超はやい
#保存
with open('test.pkl','wb') as f1:
    pickle.dump(koku_hoyu,f1)

In [7]:
#読み込み
with open('test.pkl','rb') as f2:
    data=pickle.load(f2)

In [6]:
#以下車データの読み込み
#車両データは全体取れてないので、取った後に立て結合して使う
kuruma = pd.read_csv("/Users/01017387/Desktop/しごと/data/car用/加工済み/物件*問い合わせ/tes.csv")
kuruma["b.shikuchoson_jusho_kj"] = kuruma["b.shikuchoson_jusho_kj"].str.replace('ヶ', 'ケ')

In [7]:
#県単位、市区町村単位での地方別集計（問い合わせ）
#入ってるレベル感が違う
#市区町村が最後の文字になるように調整した変数を作成する

#市区町村マスタと一致する部分のみ残す
#市区町村マスタを辞書型で作成する
#県に紐づく市区町村をリストで保持しておく
dl = pd.read_csv("/Users/01017387/Desktop/しごと/data/car用/加工済み/市区町村マスタ.csv",names=["pref","city"])

#h市区町村表記揺れを消したい
dl["city"] = dl["city"].str.replace('ヶ', 'ケ')
pre = dl["pref"].unique() #array
dl["count"] =1
num = dl.groupby("pref").sum()

dc = num.to_dict()
dic = dc["count"]

biglis = []
c=0
#都道府県別市区町村の格納
for i in pre:
    tmplis = []
    for k in range(int(dic[i])):
        exec("tmplis.append(dl['city']["+str(c)+"])")
        c +=1
    #最初の要素を最後に持ってくる
    
    push_to_last = tmplis.pop(0)
    tmplis.append(push_to_last)
    biglis.append(tmplis)

#辞書の作成
dicts = {key: value for (key, value) in zip(pre,biglis)}

#dfの各要素について、辞書のどこに一致するかを見て、ループで部分一致を探す

In [8]:
ken = kuruma["b.todofuken_jusho_kj"].values
aa = kuruma["b.shikuchoson_jusho_kj"].values
aa
bb = []
counter =[]
#市区町村を格納してる順番が良くないので、並び替えが必要
for k,i in zip(ken,aa):
    count=0
    for l in dicts[k]:
        if l in i:
            bb.append(l)
            counter.append(1)
            break
        count+=1
        if count >=(len(dicts[k])):
            bb.append("")
            counter.append(0)
            break
#概ねOKだけど、県名の後に直接郡の名前が来るケースに対応できていない
# →修正面倒なので後回し
#スクレイピングで持ってくる必要ある：　http://www.geocities.jp/je2kcr/current_allgun.htm
#bbが欠損のものはとりあえず除外検討

In [9]:
print(len(bb))
print(len(aa))
print(len(ken))
print(len(counter))
print(sum(counter))
# bb
# aa
counter.index(0)
# bb[172]
# aa[172]
print(aa[10:18])
print(bb[10:18])
# ken[172]

5000
5000
5000
5000
4799
['神戸市長田区源平町' '文京区根津' '伊勢崎市国定町' '黒部市堀切' '苫田郡' '柏市高柳' '阿蘇郡' '世田谷区等々力']
['神戸市長田区', '文京区', '伊勢崎市', '黒部市', '', '柏市', '', '世田谷区']

In [10]:
#bbをkurumaにマージ
kuruma["city_name"] = bb
kuruma["count"] = 1
#toiawase_dateの型を日付型に変更する必要ある
kuruma["toiawase_datetime"] = pd.to_datetime(kuruma["b.toiawase_date"].str[:10] + " " + kuruma["b.toiawase_date"].str[10:])
kuruma["toiawase_y"] = kuruma["toiawase_datetime"].dt.year.astype(str)
kuruma["toiawase_m"] = kuruma["toiawase_datetime"].dt.month.astype(str)
kuruma["toiawase_ym"] = kuruma["toiawase_y"] + kuruma["toiawase_m"]

# print(kuruma.columns)
kuruma.head()

,a.keisai_shashu_kj,a.keisai_grade_name,a.door_su,a.body_type_name,a.mission_flg,a.mt_mode_at_flg,a.handle_flg,a.air_conditioner_flg,a.power_steering_flg,a.power_window_flg,...,b.zip,b.hojin_cd,b.madoguchi_cd,b.yyyymmdd,city_name,count,toiawase_datetime,toiawase_y,toiawase_m,toiawase_ym
0,F355,GTS,2.0,クーペ,10,0,2,1,1,1,...,null,220294,1,20161213,横浜市神奈川区,1,2015-06-24 08:35:20,2015,6,20156
1,ピアッツァ,1.8XE/Sハンドリングバイロータス,3.0,クーペ,2,0,1,1,1,1,...,1060045,31078,1,20161213,港区,1,2016-04-26 21:33:34,2016,4,20164
2,シルビア,2.0Q’sSE,2.0,クーペ,9,0,1,1,1,1,...,null,210545,1,20161213,東大阪市,1,2015-03-03 13:38:33,2015,3,20153
3,ミニ,MK-Ⅰ仕様,3.0,ハッチバック,2,0,1,1,0,0,...,3998303,214352,4,20161213,安曇野市,1,2015-06-02 15:07:26,2015,6,20156
4,5シリーズ,525iハイライン,4.0,セダン,3,0,1,1,1,1,...,2210823,40648,1,20161213,横浜市神奈川区,1,2015-08-10 09:00:28,2015,8,20158

<b>
物件×問い合わせ元データ作成・・・ここまで<br>
物件×問い合わせ辞書作成・・・ここから<br>
（辞書じゃなくてサマった結果を民力と一緒に保持しておくのがいいかもしれない）
<b/>

In [124]:
def convert_to_city_based_num(data,colname,indice):
    out = data.reset_index().pivot(index=indice,columns=colname,values="count")
    vals = []1
    #以上値の除去
    for i in out.columns:
        vals.append(out.columns.name+"_"+str(i))
    out.columns=vals
    out[indice] = out.index
    del out.index.name
    
    return out
# .pivot(index=tmp_dt.index.names[0], columns=tmp_dt.index.names[1], values="count")

In [126]:
#都道府県
pref_summary = kuruma.groupby("b.todofuken_jusho_kj").sum()["count"]
pref_summary_dicts = {key: value for (key, value) in zip(pref_summary.index.values,pref_summary.values)}
kuruma["num_toiawase_in_pref"] = kuruma["b.todofuken_jusho_kj"].apply(pref_summary_dicts.get)

#市区町村
city_summary = kuruma.groupby("city_name").sum()["count"]
city_summary_dicts = {key: value for (key, value) in zip(city_summary.index.values,city_summary.values)}
kuruma["num_toiawase_in_city"] = kuruma["city_name"].apply(city_summary_dicts.get)

#都道府県/市区町村単位でボディタイプ、問合年月、ドア数で集計（計６パターン）
shukei_val = ["a.body_type_name", "toiawase_ym", "a.door_su"]
out_name = ["body", "month", "door",]

pref_city = ["b.todofuken_jusho_kj","city_name"]
out_preposition = ["pref", "city"]

for s,o in zip(shukei_val,out_name):
    for p,op in zip(pref_city,out_preposition):
        exec(op+'_'+o+'_summary = kuruma.groupby(["'+p+'","'+s+'"]).sum()["count"]') #groupby().sum()["count"]
        exec(op+'_'+o+'_summary_dicts = {key: value for key, value in zip('+op+'_'+o+'_summary.index.values,'+op+'_'+o+'_summary.values)}') #辞書に格納
        exec('kuruma["num_toiawase_'+o+'_in_'+p+'"] = kuruma.apply(lambda x :'+op+'_'+o+'_summary_dicts.get((x["'+p+'"],x["'+s+'"])), 1)') #変数を問い合わせに追加
        exec(o+'_by_'+op+' = convert_to_city_based_num('+op+'_'+o+'_summary'+',"'+str(s)+'","'+p+'")') #県別/市区町村別でテーブル作成

In [128]:
# pref_summary

In [23]:
#地域別集計(問い合わせ)
#全て辞書形式で持っておいて、実際の車に紐付ける形にする
#実際の元データの車種名、地域、スペックと紐付けたドア数をキーにして辞書から値を作成する

#都道府県
pref_summary = kuruma.groupby("b.todofuken_jusho_kj").sum()["count"]
pref_summary_dicts = {key: value for (key, value) in zip(pref_summary.index.values,pref_summary.values)}
kuruma["num_toiawase_in_pref"] = kuruma["b.todofuken_jusho_kj"].apply(pref_summary_dicts.get)

#市区町村
city_summary = kuruma.groupby("city_name").sum()["count"]
city_summary_dicts = {key: value for (key, value) in zip(city_summary.index.values,city_summary.values)}
kuruma["num_toiawase_in_city"] = kuruma["city_name"].apply(city_summary_dicts.get)

#以降全て市区町村単位で実施する必要あり
#辞書型にせずに民力に全てくっつける手もあるが、最終的には車単位のレコードに落ちてくる
#マルチキー形式の辞書にする

# -body_typeごと(都道府県)
pref_body_summary = kuruma.groupby(["b.todofuken_jusho_kj","a.body_type_name"]).sum()["count"]
pref_body_summary_dicts = {key: value for key, value in zip(pref_body_summary.index.values,pref_body_summary.values)}
kuruma["num_toiawase_body_in_pref"] = kuruma.apply(lambda x :pref_body_summary_dicts.get((x["b.todofuken_jusho_kj"],x["a.body_type_name"])), 1)

# -body_typeごと(市区町村)
city_body_summary = kuruma.groupby(["city_name","a.body_type_name"]).sum()["count"]
city_body_summary_dicts = {key: value for key, value in zip(city_body_summary.index.values,city_body_summary.values)}
kuruma["num_toiawase_body_in_city"] = kuruma.apply(lambda x :city_body_summary_dicts.get((x["city_name"],x["a.body_type_name"])), 1)

# -問い合わせ月ごと(都道府県)
pref_month_summary = kuruma.groupby(["b.todofuken_jusho_kj","toiawase_ym"]).sum()["count"]
pref_month_summary_dicts = {key: value for key, value in zip(pref_month_summary.index.values,pref_month_summary.values)}
kuruma["num_month_in_pref"] = kuruma.apply(lambda x :pref_month_summary_dicts.get((x["b.todofuken_jusho_kj"],x["toiawase_ym"])), 1)
# -問い合わせ月ごと(市区町村)
city_month_summary = kuruma.groupby(["city_name","toiawase_ym"]).sum()["count"]
city_month_summary_dicts = {key: value for key, value in zip(city_month_summary.index.values,city_month_summary.values)}
kuruma["num_month_in_city"] = kuruma.apply(lambda x :city_month_summary_dicts.get((x["city_name"],x["toiawase_ym"])), 1)
#おまけ：ドア数単位(都道府県)
pref_door_summary = kuruma.groupby(["b.todofuken_jusho_kj","a.door_su"]).sum()["count"]
pref_door_summary_dicts = {key: value for key, value in zip(pref_door_summary.index.values,pref_door_summary.values)}
kuruma["num_door_in_pref"] = kuruma.apply(lambda x :pref_door_summary_dicts.get((x["b.todofuken_jusho_kj"],x["a.door_su"])), 1)
#おまけ：ドア数単位(市区町村)
city_door_summary = kuruma.groupby(["city_name","a.door_su"]).sum()["count"]
city_door_summary_dicts = {key: value for key, value in zip(city_door_summary.index.values,city_door_summary.values)}
kuruma["num_door_in_city"] = kuruma.apply(lambda x :city_door_summary_dicts.get((x["city_name"],x["a.door_su"])), 1)

#市区町村単位のデータも作成しておく

In [107]:
#車種・グレード別集計（問い合わせ）
# -車種ごと
shashu_summary = kuruma.groupby("a.keisai_shashu_kj").sum()["count"]
shashu_summary_dicts = {key: value for (key, value) in zip(shashu_summary.index.values,shashu_summary.values)}
kuruma["num_shashu"] = kuruma["a.keisai_shashu_kj"].apply(shashu_summary_dicts.get)
# -車種&グレードごと
shashu_grade_summary = kuruma.groupby(["a.keisai_shashu_kj","a.keisai_grade_name"]).sum()["count"]
shashu_grade_summary_dicts = {key: value for (key, value) in zip(shashu_grade_summary.index.values,shashu_grade_summary.values)}
kuruma["num_shashu_grade"] = kuruma.apply(lambda x :shashu_grade_summary_dicts.get((x["a.keisai_shashu_kj"],x["a.keisai_grade_name"])), 1)
#body_typeごと
body_summary = kuruma.groupby("a.body_type_name").sum()["count"]
body_summary_dicts = {key: value for (key, value) in zip(body_summary.index.values,body_summary.values)}
kuruma["num_body_type"] = kuruma["a.body_type_name"].apply(body_summary_dicts.get)
#おまけ：ドア数単位
door_summary = kuruma.groupby("a.door_su").sum()["count"]
door_summary_dicts = {key: value for (key, value) in zip(door_summary.index.values,door_summary.values)}
kuruma["num_door"] = kuruma["a.door_su"].apply(door_summary_dicts.get)
#車種・グレード別集計（お気に入り）

In [13]:
#必要そうな変数は準備した
#とりあえず加工前のものをマージしにかかる
# kuruma.head().T
# kuruma.columns

In [14]:
#辞書との連携が死ぬほど楽になる
#apply(辞書.get)で値を入れられる
# del kuruma["aa"]

<b>------------------------------問い合わせデータ＆辞書作成ーここまで------------------------------<b/><br>
<b>------------------------------お気に入りデータ作成ー開始---------------------------<b/>

In [16]:
#accessDBの形なので、取り込みを頑張る必要あり
#→無理なのでWinでcsvにしてから取り込むことに

<b>------------------------------お気に入りデータ作成ーここまで------------------------------<b/><br>
<b>------------------------------カスタマDB作成ー開始---------------------------<b/>

In [13]:
cus = pd.read_csv("/Users/01017387/Desktop/しごと/data/car用/cus_db.csv")

In [14]:
cus.head()
cus["count"] = 1
cus.shape
# cus.columns
# tes = cus.head(1000)

(100000, 109)

In [15]:
# 予測含め、地域が入ってないものを捨てる
# 予測精度約７割程度はあるので、まあいいかなと
city_drop_na = cus.dropna(subset=['pref_integration_cd'])
#実際のデータセットはpref_integration_nmで作成する

In [16]:
#地域単位でサマる、フラグ系は割合に直して持ちたい

In [17]:
#フラグについては、とりあえず８割以上の確率が入っているものor真の値が入っているものを使う
#幼児フラグはあるものだけ使う
#フラグ対象：小学生以下子供フラグ、社会人フラグ、性別、カップル、
# have_child_integration_flg, sex_integration, age_integration_cd, high_income_predict_flg,
# businessperson_integration_flg, couple_flg, have_baby_flg, 
# car系フラグ #suumoはほとんど入ってないからもはや入れない
# car_1w_pv_flg, car_1m_pv_flg, car_3m_pv_flg, car_6m_pv_flg, car_12m_pv_flg 

#セグメント分布(アクセス時間帯＋休日、平日とか)
# sp_holiday_flg
# sp_weekday_flg
# pc_holiday_flg
# pc_weekday_flg
# holiday_flg
# weekday_flg
# sp_holiday_time_seg
# sp_weekday_time_seg
# pc_holiday_time_seg
# pc_weekday_time_seg
# holiday_time_seg
# weekday_time_seg
# weekday_device_seg

#年収、年齢等の数値変数系は平均と中央値を入れる
# annual_income_predict_value, annual_income_integration_cd,  age_integration_value,

# 市区町村（そもそも埋まってる割合がやや低めなので、難しそうだけど）
# city_integration_nm_1 ~ 3は一回見てみる必要がある
# →精度がえらい低い（27%）なので使わない方がいいかも

#cus_dbのよさ
# →収入がより細かく見れるようになる
# →幼児、小学生以下の子供とか、子供系がもう少し細かく見れる
#Rのサービスユーザ、というバイアスをかけて対象を観察できる
#セグメント分布を見れるようになる

In [18]:
tmp_dt = city_drop_na.ix[:,["count","have_child_integration_flg",
                            "pref_integration_nm"]].groupby(["pref_integration_nm","have_child_integration_flg"]).sum()
#県別にフラグの値をカウント
merged = tmp_dt.reset_index().pivot(index=tmp_dt.index.names[0], columns=tmp_dt.index.names[1], values="count")
lis = []
for i in merged.columns:
    lis.append(str(merged.columns.name)+"_"+str(i))
merged.columns = lis
del merged.index.name
merged["pref"] = merged.index
# merged.head()

#変数を動的に与えて、ループでデータセットを作成＆append
#フラグ系対象変数
#sp系は数値が入っていないので、最初は抜いて試す
# iter_target = ["sex_integration", "age_integration_cd", "high_income_predict_flg",
#                "businessperson_integration_flg", "couple_flg", "have_baby_flg", "car_1w_pv_flg", "car_1m_pv_flg", "car_3m_pv_flg",
#                "car_6m_pv_flg", "car_12m_pv_flg", "sp_holiday_flg", "sp_weekday_flg", "pc_holiday_flg", "pc_weekday_flg", "holiday_flg",
#                "weekday_flg", "sp_holiday_time_seg", "sp_weekday_time_seg", "pc_holiday_time_seg", "pc_weekday_time_seg",
#                "holiday_time_seg", "weekday_time_seg", "weekday_device_seg"]
iter_target = ["sex_integration", "age_integration_cd", "high_income_predict_flg",
               "businessperson_integration_flg", "couple_flg", "have_baby_flg", "car_1w_pv_flg", "car_1m_pv_flg", "car_3m_pv_flg",
               "car_6m_pv_flg", "car_12m_pv_flg"]

loop_count = 0
for i in iter_target:
    loop_count +=1
    exec('tmp_dt = city_drop_na.ix[:,["count","'+str(i)+'","pref_integration_nm"]].groupby(["pref_integration_nm","'+str(i)+'"]).sum()')
    #県別にフラグの値をカウント
    tmp = tmp_dt.reset_index().pivot(index=tmp_dt.index.names[0], columns=tmp_dt.index.names[1], values="count")
    tmp_rate = tmp.copy()/len(city_drop_na)
    #一時対応策：カラム名が同一になってしまい、後で不都合が起こるので、一時的に適当なカラム名を与える
    tmp_lis = (np.array(list(range(len(tmp_rate.T))))+1)*10
    tmp_rate.columns=tmp_lis
    
    lis = []
    for n in range(2):
        for i in tmp.columns:
            if n == 0:
                lis.append(str(tmp.columns.name)+"_"+str(i))
            if n == 1:
                lis.append(str(tmp.columns.name)+"_"+str(i)+"_rate")
    
    tmp = pd.concat([tmp,tmp_rate],axis=1)
    tmp.columns = lis
    del tmp.index.name
    tmp["pref"] = tmp.index
    #率も入れる
    
    #できたものを元のデータセットにマージしていく
    merged = pd.merge(merged,tmp,on="pref")
#     if loop_count >=11:
#         break

In [19]:
#数値系の統合(年収、年齢)
num_loop = ["annual_income_predict_value", "annual_income_integration_cd", "age_integration_value"]

for l in num_loop:
    exec('tmp_mean = city_drop_na.ix[:,["'+str(l)+'","pref_integration_nm"]].groupby(["pref_integration_nm"]).mean()')
    exec('tmp_med = city_drop_na.ix[:,["'+str(l)+'","pref_integration_nm"]].groupby(["pref_integration_nm"]).median()')
    exec('tmp_mean.columns = ["'+str(l)+'"+"_mean"]')
    exec('tmp_med.columns  = ["'+str(l)+'"+"_med"]')
    tmp_mean["pref"] = tmp_mean.index
    tmp_med["pref"] = tmp_med.index
    merged = pd.merge(merged,tmp_mean,on="pref")
    merged = pd.merge(merged,tmp_med,on="pref")

In [20]:
cus_extracted = merged.copy()
cus_extracted = cus_extracted.rename(columns={"pref":"chiho"})
cus_extracted.head()

,have_child_integration_flg_0,have_child_integration_flg_1,chiho,sex_integration_0,sex_integration_1,sex_integration_0_rate,sex_integration_1_rate,age_integration_cd_0,age_integration_cd_5,age_integration_cd_10,...,car_12m_pv_flg_0,car_12m_pv_flg_1,car_12m_pv_flg_0_rate,car_12m_pv_flg_1_rate,annual_income_predict_value_mean,annual_income_predict_value_med,annual_income_integration_cd_mean,annual_income_integration_cd_med,age_integration_value_mean,age_integration_value_med
0,452,240,その他,397,295,0.005210,0.003871,NaN,NaN,1.0,...,682,10,0.008950,0.000131,2.927857,2.412347,2.468208,2,38.354046,37.0
1,685,251,三重県,433,503,0.005682,0.006601,NaN,NaN,NaN,...,885,51,0.011614,0.000669,3.291864,2.677858,2.789530,2,40.691239,39.0
2,1157,360,京都府,738,779,0.009685,0.010223,NaN,NaN,NaN,...,1438,79,0.018871,0.001037,3.338074,2.614099,2.862228,2,40.673039,39.0
3,229,96,佐賀県,173,152,0.002270,0.001995,NaN,NaN,NaN,...,310,15,0.004068,0.000197,3.022071,2.297181,2.560000,2,38.670769,37.0
4,2635,929,兵庫県,1750,1814,0.022966,0.023805,NaN,1.0,1.0,...,3381,183,0.044369,0.002402,3.459395,2.722141,2.947250,2,40.674804,39.0

In [21]:
#最後に市区町村単位にサマッたカスタマDBを民力にマージする
koku_hoyu_cusdb = pd.merge(koku_hoyu,cus_extracted,on="chiho")
koku_hoyu_cusdb.head()

,pref_code,pref_city_code,capital_city_flg,city_categories,chiho,city_name,population,h22_kumikae_population,population_changed_from_h22_to_h27,rate_population_changed_from_h22_to_h27,...,car_12m_pv_flg_0,car_12m_pv_flg_1,car_12m_pv_flg_0_rate,car_12m_pv_flg_1_rate,annual_income_predict_value_mean,annual_income_predict_value_med,annual_income_integration_cd_mean,annual_income_integration_cd_med,age_integration_value_mean,age_integration_value_med
0,1.0,1100.0,1.0,1.0,北海道,札幌市,"1,952,356","1,913,545","38,811",2.0,...,3456,204,0.045354,0.002677,3.189625,2.6372,2.717213,2,40.027869,38.0
1,1.0,1101.0,NaN,0.0,北海道,札幌市中央区,"237,627","220,189","17,438",7.9,...,3456,204,0.045354,0.002677,3.189625,2.6372,2.717213,2,40.027869,38.0
2,1.0,1102.0,NaN,0.0,北海道,札幌市北区,"285,321","278,781","6,540",2.3,...,3456,204,0.045354,0.002677,3.189625,2.6372,2.717213,2,40.027869,38.0
3,1.0,1103.0,NaN,0.0,北海道,札幌市東区,"261,912","255,873","6,039",2.4,...,3456,204,0.045354,0.002677,3.189625,2.6372,2.717213,2,40.027869,38.0
4,1.0,1104.0,NaN,0.0,北海道,札幌市白石区,"209,584","204,259","5,325",2.6,...,3456,204,0.045354,0.002677,3.189625,2.6372,2.717213,2,40.027869,38.0

<b>------------------------------カスタマDB作成ーここまで---------------------------<br>
------------------------------市区町村名と対応した辞書作成作成ー開始---------------------------<br>
<b/>

<b>
------------------------------市区町村名と対応した辞書作成作成ー終わり---------------------------<br>
------------------------------成約データ読み込みー開始---------------------------<br>
<b/>

In [22]:
t = pd.read_csv("/Users/01017387/Desktop/いろいろ/raw_data.csv",delimiter=" ")
t.head()
# t.columns
#shashuとchihoに上段で作成したデータを紐付ける

,wns_bukken_cd,shinkoyo_nohimbi_cd,hojin_cd,madoguchi_cd,chiho,coupon_flg,fair_flg,sd_flg,kuchikomi_flg,maker_name,...,y_cs,p_cs,y_other,p_other,kuchikomi_cnt,katashiki,cnt_total_price,avg_total_price,min_total_price,predicted_price
810772,U00012656926,150102,303968,1,福岡県,1,0,0,1,ダイハツ,...,0,0.037452,0,0.148028,4,LA-L152S,445,3.382966e+05,80000.0,3.140288e+05
5301564,UZ0014935617,150403,219007,1,山梨県,0,0,0,1,ホンダ,...,0,0.074008,0,0.120010,4,DBA-KB2,1,3.212000e+06,3212000.0,2.410772e+06
4924075,UZ0013173022,141107,51721,115,宮城県,1,1,0,1,スバル,...,0,0.026905,0,0.124821,16,DBA-RJ2,156,1.082494e+06,328000.0,1.041860e+06
4500543,UD0015293572,150703,81727,5,滋賀県,0,0,0,0,スズキ,...,0,0.011554,0,0.144302,0,DBA-MA15S,72,1.242056e+06,739000.0,9.695125e+05
4635857,UJ0013369648,141003,30121,1,愛知県,1,1,0,1,三菱,...,0,0.032983,0,0.286805,54,GBD-U61V,1001,7.178082e+05,150000.0,4.494569e+05

<b>
------------------------------成約データ読み込みー終わり---------------------------<br>
------------------------------データ読み込みステップー終わり---------------------------<br>
<b/>