In [77]:
import pandas as pd
import numpy as np
import pickle

In [2]:
#面倒な前処理部分は今回エクセル上で実施済み
#別途前処理をするコードが必要
#

In [3]:
#国勢調査
kokusei = pd.read_csv("/Users/01017387/Desktop/しごと/data/car用/加工済み/kokuseichosa_2015_for_merge.csv")
print(kokusei.columns)
#全てを英字変換する必要あり
kokusei.columns=["pref_code", "pref_city_code", "capital_city_flg", "city_categories", "chiho", "city_name",
                 "population", "h22_kumikae_population", "population_changed_from_h22_to_h27", "rate_population_changed_from_h22_to_h27",
                 "gross_area", "population_density", "ave_age_from_h22_to_h27", "med_age_from_h22_to_h27", "population",
                 "population_under_15old", "population_from_15_to_64_old", "population_over_65old", "rate_population_under_15_year_old",
                 "rate_population_from_15_to_64_old", "rate_population_over_65old", "population_male","population_male_under_15old",
                 "population_male_from_15_to_64_old", "population_male_over_65old", "rate_population_male_under_15old",
                 "rate_population_male_from_15_to_64_old", "rate_population_male_over_65old", "population_female",
                 "population_female_under_15old", "population_female_from_15_to_64_old", "population_female_over_65old",
                 "rate_population_female_under_15old", "rate_population_female_from_15_to_64_old", "rate_population_female_over_65old",
                 "rate_population_male_to female", "population_jap", "population_no_jap", "num_of_family", "num_of_normal_family",
                 "num_of_family_in_facilities", "h22_kumikae_family", "num_of_normal_family", "num_of_nuclear_family",
                 "num_of_family_no_children", "num_of_family_with_children", "num_of_father_and_children", "num_of_mother_and_children",
                 "num_of_singles", "num_of_over_65old_singles", "num_of_old_married_couples_no_children", "num_of_3generation_family",]
kokusei.columns
print(kokusei.shape)
kokusei.head()

Index(['都道府県\rコード', '都道府県・\r市区町村コード', '都道府県庁\r所在市', '市など\rの別', '都道府県名',
       '都道府県・市区町村名', '人口総数', '平成22年組替人口', '平成22年～27年の人口増減数', '平成22年～27年の人口増減率',
       '平成22年～27年の面積', '平成22年～27年の人口密度', '平成22年～27年の平均年齢', '平成22年～27年の年齢中位数',
       '年齢（総数）総数\r人口', '年齢（総数）15歳未満\r人口', '年齢（総数）15～64歳\r人口',
       '年齢（総数）65歳以上\r人口', '年齢別割合（総数）15歳未満\r人口割合', '年齢別割合（総数）15～64歳\r人口割合',
       '年齢別割合（総数）65歳以上\r人口割合', '年齢（男）総数\r人口', '年齢（男）15歳未満\r人口',
       '年齢（男）15～64歳\r人口', '年齢（男）65歳以上\r人口', '年齢別割合（男）15歳未満\r人口割合',
       '年齢別割合（男）15～64歳\r人口割合', '年齢別割合（男）65歳以上\r人口割合', '年齢（女）総数\r人口',
       '年齢（女）15歳未満\r人口', '年齢（女）15～64歳\r人口', '年齢（女）65歳以上\r人口',
       '年齢別割合（女）15歳未満\r人口割合', '年齢別割合（女）15～64歳\r人口割合', '年齢別割合（女）65歳以上\r人口割合',
       '年齢別割合（女）人口性比（女100人につき男）', '日本人', '外国人', '世帯総数', '一般世帯', '施設等の世帯',
       '平成22年組替世帯総数', '一般世帯数', '一般世帯数うち\r核家族世帯', '一般世帯数うち\r夫婦のみの世帯',
       '一般世帯数うち\r夫婦と子供\rから成る世帯', '一般世帯数うち\r男親と子供\rから成る世帯',
       '一般世帯数うち\r女親と子供\rから成る世帯', '一般世帯数うち\r単独世帯', '一般世帯数うち\r65歳以上の高齢単身者世帯',
       '一般世帯数（再掲）\r高齢夫婦世帯\r（夫65歳以上妻60歳以上の夫婦1組のみの一般世帯）', '一般世帯数（再掲）\r３世代世帯'],
      dtype='object')
(1959, 52)

,pref_code,pref_city_code,capital_city_flg,city_categories,chiho,city_name,population,h22_kumikae_population,population_changed_from_h22_to_h27,rate_population_changed_from_h22_to_h27,...,num_of_normal_family,num_of_nuclear_family,num_of_family_no_children,num_of_family_with_children,num_of_father_and_children,num_of_mother_and_children,num_of_singles,num_of_over_65old_singles,num_of_old_married_couples_no_children,num_of_3generation_family
0,1.0,1100.0,1.0,1.0,北海道,札幌市,"1,952,356","1,913,545","38,811",2.0,...,"920,415","493,644","194,424","213,793","10,049","75,378","375,242","104,650","98,660","20,124"
1,1.0,1101.0,NaN,0.0,北海道,札幌市中央区,"237,627","220,189","17,438",7.9,...,"131,819","52,695","22,332","21,118",878,"8,367","73,164","14,403","9,542","1,221"
2,1.0,1102.0,NaN,0.0,北海道,札幌市北区,"285,321","278,781","6,540",2.3,...,"133,477","70,121","26,738","31,744","1,414","10,225","55,247","14,688","14,221","3,164"
3,1.0,1103.0,NaN,0.0,北海道,札幌市東区,"261,912","255,873","6,039",2.4,...,"124,251","65,606","24,770","28,880","1,401","10,555","51,879","14,050","12,156","2,504"
4,1.0,1104.0,NaN,0.0,北海道,札幌市白石区,"209,584","204,259","5,325",2.6,...,"104,464","51,433","19,992","21,661","1,232","8,548","47,852","11,906","8,994","1,920"

In [4]:
#保有台数
hoyu = pd.read_csv("/Users/01017387/Desktop/しごと/data/car用/加工済み/2015_hoyu_daisu.csv",encoding="utf-8")
print(hoyu.columns)
hoyu.columns = ["chiho", "num_of_cars_all", "num_of_cars_kei", "num_of_cars_normal", "num_of_familiy", "cars_per_person",
                "normal_cars_per_person", "kei_cars_per_person", "kei_rate", "normal_rate", "kei_share_in_JP", "normal_share_in_JP",
                "guess_2nd_hand_kei_car_sales_per_year", "guess_2nd_hand_normal_car_sales_per_year", "guess_2nd_hand_car_all_sales_per_year"]
print(hoyu.shape)
hoyu.head()

Index(['都道府県名', '乗用車', '軽', '普通', '世帯数', '車両数/世帯数', '普通車両数/世帯数', '軽車両数/世帯数',
       '軽率', '普通率', '軽シェア', '普通シェア', '軽シェア×中古販売数', '普通シェア×中古販売数', '中古車販売台数'],
      dtype='object')
(47, 15)

,chiho,num_of_cars_all,num_of_cars_kei,num_of_cars_normal,num_of_familiy,cars_per_person,normal_cars_per_person,kei_cars_per_person,kei_rate,normal_rate,kei_share_in_JP,normal_share_in_JP,guess_2nd_hand_kei_car_sales_per_year,guess_2nd_hand_normal_car_sales_per_year,guess_2nd_hand_car_all_sales_per_year
0,北海道,"2,805,265",1142062,"1,663,203","2,734,906",1.025726,0.608139,0.417587,40.71%,59.29%,3.77%,5.39%,"37,693","161,743","199,436"
1,青森,"728,253",455493,"272,760","586,148",1.242439,0.465343,0.777096,62.55%,37.45%,1.50%,0.88%,"15,033","26,525","41,559"
2,岩手,"738,199",458943,"279,256","517,845",1.425521,0.539266,0.886256,62.17%,37.83%,1.51%,0.91%,"15,147","27,157","42,304"
3,宮城,"1,282,869",617560,"665,309","961,574",1.334134,0.691896,0.642239,48.14%,51.86%,2.04%,2.16%,"20,382","64,700","85,082"
4,秋田,"594,158",374063,"220,095","424,208",1.400629,0.518837,0.881791,62.96%,37.04%,1.23%,0.71%,"12,346","21,404","33,749"

In [5]:
#保有台数のキーの変更
# hoyu.rename(columns={"県名":"都道府県名"})
hoyu.head(2)
# hoyu["県名"]
#国勢調査と保有台数のマージ
koku_hoyu = pd.merge(kokusei,hoyu,on="chiho",how="left")
print(koku_hoyu.shape)
koku_hoyu.head()
#OK

(1959, 66)

,pref_code,pref_city_code,capital_city_flg,city_categories,chiho,city_name,population,h22_kumikae_population,population_changed_from_h22_to_h27,rate_population_changed_from_h22_to_h27,...,cars_per_person,normal_cars_per_person,kei_cars_per_person,kei_rate,normal_rate,kei_share_in_JP,normal_share_in_JP,guess_2nd_hand_kei_car_sales_per_year,guess_2nd_hand_normal_car_sales_per_year,guess_2nd_hand_car_all_sales_per_year
0,1.0,1100.0,1.0,1.0,北海道,札幌市,"1,952,356","1,913,545","38,811",2.0,...,1.025726,0.608139,0.417587,40.71%,59.29%,3.77%,5.39%,"37,693","161,743","199,436"
1,1.0,1101.0,NaN,0.0,北海道,札幌市中央区,"237,627","220,189","17,438",7.9,...,1.025726,0.608139,0.417587,40.71%,59.29%,3.77%,5.39%,"37,693","161,743","199,436"
2,1.0,1102.0,NaN,0.0,北海道,札幌市北区,"285,321","278,781","6,540",2.3,...,1.025726,0.608139,0.417587,40.71%,59.29%,3.77%,5.39%,"37,693","161,743","199,436"
3,1.0,1103.0,NaN,0.0,北海道,札幌市東区,"261,912","255,873","6,039",2.4,...,1.025726,0.608139,0.417587,40.71%,59.29%,3.77%,5.39%,"37,693","161,743","199,436"
4,1.0,1104.0,NaN,0.0,北海道,札幌市白石区,"209,584","204,259","5,325",2.6,...,1.025726,0.608139,0.417587,40.71%,59.29%,3.77%,5.39%,"37,693","161,743","199,436"

In [43]:
#pickle形式でdataframeを保存
#超はやい
#保存
with open('test.pkl','wb') as f1:
    pickle.dump(koku_hoyu,f1)

In [45]:
#読み込み
with open('test.pkl','rb') as f2:
    data=pickle.load(f2)

In [55]:
#以下車データの読み込み
kuruma = pd.read_csv("/Users/01017387/Desktop/しごと/data/car用/加工済み/物件*問い合わせ/tes.csv")
kuruma["b.shikuchoson_jusho_kj"] = kuruma["b.shikuchoson_jusho_kj"].str.replace('ヶ', 'ケ')
kuruma.head()
kuruma.tail()

,a.keisai_shashu_kj,a.keisai_grade_name,a.door_su,a.body_type_name,a.mission_flg,a.mt_mode_at_flg,a.handle_flg,a.air_conditioner_flg,a.power_steering_flg,a.power_window_flg,...,a.hdd_navigation_flg,a.katashiki,b.toiawase_date,b.todofuken_cd,b.todofuken_jusho_kj,b.shikuchoson_jusho_kj,b.zip,b.hojin_cd,b.madoguchi_cd,b.yyyymmdd
4995,ハイエース,2.7GLロングミドルルーフ,4.0,ミニバン,26,0,1,1,1,1,...,1,CBA-TRH214W,2015-09-3016:22:47,36,神奈川県,横浜市青葉区桜台,2270061,81702,1,20161213
4996,ハイエース,2.7GLロングミドルルーフ,4.0,ミニバン,26,0,1,1,1,1,...,1,CBA-TRH214W,2015-11-0913:19:48,25,福島県,相馬郡新地町小川,9792703,81702,1,20161213
4997,スカイラインクーペ,3.5350GT,2.0,クーペ,3,1,1,1,1,1,...,0,UA-CPV35,2015-07-0115:17:05,63,広島県,呉市広津久茂町,null,307963,1,20161213
4998,マーチ,1.212c,5.0,ハッチバック,2,0,1,1,1,1,...,0,CBA-AK12,2015-02-0220:47:21,33,埼玉県,所沢市,null,307963,1,20161213
4999,マーチ,1.212c,5.0,ハッチバック,2,0,1,1,1,1,...,0,CBA-AK12,2015-02-0318:45:06,33,埼玉県,入間市宮寺,3580014,307963,1,20161213

In [81]:
#県単位、市区町村単位での地方別集計（問い合わせ）
#入ってるレベル感が違う
#市区町村が最後の文字になるように調整した変数を作成する

#市区町村マスタと一致する部分のみ残す
#市区町村マスタを辞書型で作成する
#県に紐づく市区町村をリストで保持しておく
dl = pd.read_csv("/Users/01017387/Desktop/しごと/data/car用/加工済み/市区町村マスタ.csv",names=["pref","city"])
dl.head()

#h市区町村表記揺れを消したい
dl["city"] = dl["city"].str.replace('ヶ', 'ケ')

pre = dl["pref"].unique() #array

dl["count"] =1
num = dl.groupby("pref").sum()

dc = num.to_dict()
dic = dc["count"]

biglis = []
c=0
#都道府県別市区町村の格納
for i in pre:
    tmplis = []
    for k in range(int(dic[i])):
        exec("tmplis.append(dl['city']["+str(c)+"])")
        c +=1
    #最初の要素を最後に持ってくる
    
    push_to_last = tmplis.pop(0)
    tmplis.append(push_to_last)
    biglis.append(tmplis)

#辞書の作成
dicts = {key: value for (key, value) in zip(pre,biglis)}

#dfの各要素について、辞書のどこに一致するかを見て、ループで部分一致を探す

In [52]:
#車種・グレード別集計（問い合わせ）
#車種・グレード別集計（お気に入り）

In [57]:
ken = kuruma["b.todofuken_jusho_kj"].values
aa = kuruma["b.shikuchoson_jusho_kj"].values
aa
bb = []
counter =[]
#市区町村を格納してる順番が良くないので、並び替えが必要
for k,i in zip(ken,aa):
    count=0
    for l in dicts[k]:
        if l in i:
            bb.append(l)
            counter.append(1)
            break
        count+=1
        if count >=(len(dicts[k])):
            bb.append("")
            counter.append(0)
            break
#概ねOKだけど、県名の後に直接郡の名前が来るケースに対応できていない
→修正する？

In [58]:
print(len(bb))
print(len(aa))
print(len(ken))
print(len(counter))
print(sum(counter))
# bb
# aa
counter.index(0)
# bb[172]
# aa[172]
print(aa[10:18])
print(bb[10:18])
# ken[172]

5000
5000
5000
5000
4799
['神戸市長田区源平町' '文京区根津' '伊勢崎市国定町' '黒部市堀切' '苫田郡' '柏市高柳' '阿蘇郡' '世田谷区等々力']
['神戸市長田区', '文京区', '伊勢崎市', '黒部市', '', '柏市', '', '世田谷区']

In [76]:
ar = np.array([aa,bb,counter])
ar
an = pd.DataFrame([aa,bb,counter]).T
an.columns=["元","変更後","見つかった？"]
an.head()
ann =an.ix[an["見つかった？"] ==0].ix[an["元"] !="null"]

import japandas as jpd
ann["元1"] = ann["元"].str.z2h(kana=False, alpha=False, digit=True)
sakana = ann.ix[ann["元1"].str.extract('([0-9]+)').notnull()]
sakana

/Users/01017387/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:10: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)

                     元 変更後 見つかった？                元1
194            １５０００３３          0           1500033
548            １６９００６２          0           1690062
1045           ０６４０９５３          0           0640953
1244          ９１９−１３２４          0          919−1324
2414  南会津郡桧枝岐村字下ノ原１００４          0  南会津郡桧枝岐村字下ノ原1004
3253          ００１−０９２４          0          001−0924

In [104]:
po = pd.read_csv("/Users/01017387/Downloads/all.txt",encoding="cp932")
# 全部載ってそうなので、郡とか村の取り残しにはこっちを使う
#県と番号を対応させる
uni_pref = dl["pref"].unique()
pref_num = list(range(47))
pref_dicts = {key: value for (key, value) in zip(pref_num,uni_pref)}

#
po["code"] = ((po["団体コード"]/10000)-1).astype(int)
#１回リストを作成してからくっつける必要ある
ken_list = []
for i in po["code"].values:
    ken_list.append(pref_dicts[i])

kens = pd.DataFrame(ken_list,columns=["pref"])
po2 = pd.concat([po,kens],axis=1).dropna().ix[:,["pref","団体名"]]
po2.head()

  pref     団体名
1  北海道     札幌市
2  北海道  札幌市中央区
3  北海道   札幌市北区
4  北海道   札幌市東区
5  北海道  札幌市白石区

In [106]:
print(len(dl))
print(len(po2))
"苫田郡" in po2["団体名"].values

1916
1916

False