In [12]:
import pandas as pd
import numpy as np
import itertools


def movie_preprocessing(movie):
    movie_col = list(movie.columns)
    movie_tag = [doc.split('|') for doc in movie['tag']]
    tag_table = {token: idx for idx, token in enumerate(set(itertools.chain.from_iterable(movie_tag)))}
#     print(tag_table.items())
#     print(movie_tag)
    movie_tag = pd.DataFrame(movie_tag)
    tag_table = pd.DataFrame(list(tag_table.items()))
#     tag_table = pd.DataFrame(tag_table)
    tag_table.columns = ['Tag', 'Index']

    # use one-hot encoding for movie genres (here called tag)
    tag_dummy = np.zeros([len(movie), len(tag_table)])

    for i in range(len(movie)):
        for j in range(len(tag_table)):
            if tag_table['Tag'][j] in list(movie_tag.iloc[i, :]):
                tag_dummy[i, j] = 1

    # combine the tag_dummy one-hot encoding table to original movie files
    movie = pd.concat([movie, pd.DataFrame(tag_dummy)], 1)
    movie_col.extend(['tag' + str(i) for i in range(len(tag_table))])
    movie.columns = movie_col
    movie = movie.drop('tag', 1)
    return movie


def feature_extraction(data):
    # actions: we use top 50 movies as our actions for recommendations
    #top50のタイトルをまとめてリスト化
    actions = data.groupby('movie_id').size().sort_values(ascending=False)[:50]
    actions = list(actions.index)

    #ユーザごとに見た映画のジャンルの和を標準化したものを与えている（TOP50に入っている映画は対象外）
    # user_feature: tags they've watched for non-top-50 movies normalized per user
    user_feature = data[~data['movie_id'].isin(actions)]
    print(user_feature.head())
    user_feature = user_feature.groupby('user_id').aggregate(np.sum)
    user_feature = user_feature.drop(['movie_id', 'rating', 'timestamp'], 1)
    user_feature = user_feature.div(user_feature.sum(axis=1), axis=0)

    #top50に入っている映画のみを抽出、タイムスタンプ順に並び替えてユーザIDのみを抽出
    # streaming_batch: the result for testing bandit algrorithms
    top50_data = data[data['movie_id'].isin(actions)]
    top50_data = top50_data.sort('timestamp', ascending=1)
    #user_idだけを並べている
    streaming_batch = top50_data['user_id']

    #レートが3以上ならrewardに１を格納、そうでなければ0を格納
    # reward_list: if rating >=3, the user will watch the movie
    top50_data['reward'] = np.where(top50_data['rating'] >= 3, 1, 0)
    reward_list = top50_data[['user_id', 'movie_id', 'reward']]
    reward_list = reward_list[reward_list['reward'] == 1]
    return streaming_batch, user_feature, actions, reward_list, top50_data


def main():
    # read and preprocess the movie data
    movie = pd.read_table('/Users/01017387/Desktop/git関連/pydata-book/ch02/movielens/movies.dat', sep='::', names=['movie_id', 'movie_name', 'tag'], engine='python')
    movie = movie_preprocessing(movie)

    # read the ratings data and merge it with movie data
    rating = pd.read_table("/Users/01017387/Desktop/git関連/pydata-book/ch02/movielens/ratings.dat", sep="::",
                           names=["user_id", "movie_id", "rating", "timestamp"], engine='python')
    data = pd.merge(rating, movie, on="movie_id")

    # extract feature from our data set
    streaming_batch, user_feature, actions, reward_list, top50_data = feature_extraction(data)
    #user_id
    streaming_batch.to_csv("streaming_batch.csv", sep='\t', index=False)
    #
    user_feature.to_csv("user_feature.csv", sep='\t')
    pd.DataFrame(actions, columns=['movie_id']).to_csv("actions.csv", sep='\t', index=False)
    reward_list.to_csv("reward_list.csv", sep='\t', index=False)

    action_context = movie[movie['movie_id'].isin(actions)]
    action_context.to_csv("action_context.csv", sep='\t', index = False)
    top50_data.to_csv("top50_data.csv", sep='\t', index = False)

if __name__ == '__main__':
    main()

      user_id  movie_id  rating  timestamp                        movie_name  \
1725        1       661       3  978302109  James and the Giant Peach (1996)
1726       23       661       2  978460739  James and the Giant Peach (1996)
1727       49       661       3  977972750  James and the Giant Peach (1996)
1728       53       661       5  977979726  James and the Giant Peach (1996)
1729       57       661       4  977935511  James and the Giant Peach (1996)

      tag0  tag1  tag2  tag3  tag4  ...    tag8  tag9  tag10  tag11  tag12  \
1725   0.0   1.0   0.0   0.0   0.0  ...     0.0   0.0    0.0    0.0    0.0
1726   0.0   1.0   0.0   0.0   0.0  ...     0.0   0.0    0.0    0.0    0.0
1727   0.0   1.0   0.0   0.0   0.0  ...     0.0   0.0    0.0    0.0    0.0
1728   0.0   1.0   0.0   0.0   0.0  ...     0.0   0.0    0.0    0.0    0.0
1729   0.0   1.0   0.0   0.0   0.0  ...     0.0   0.0    0.0    0.0    0.0

      tag13  tag14  tag15  tag16  tag17
1725    0.0    0.0    0.0    0.0    1.0
1726    0.0    0.0    0.0    0.0    1.0
1727    0.0    0.0    0.0    0.0    1.0
1728    0.0    0.0    0.0    0.0    1.0
1729    0.0    0.0    0.0    0.0    1.0

[5 rows x 23 columns]

/Users/01017387/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:50: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

In [2]:
# read and preprocess the movie data
movie = pd.read_table('/Users/01017387/Desktop/git関連/pydata-book/ch02/movielens/movies.dat', sep='::', names=['movie_id', 'movie_name', 'tag'], engine='python')
movie = movie_preprocessing(movie)

# read the ratings data and merge it with movie data
rating = pd.read_table("/Users/01017387/Desktop/git関連/pydata-book/ch02/movielens/ratings.dat", sep="::",
                       names=["user_id", "movie_id", "rating", "timestamp"], engine='python')
data = pd.merge(rating, movie, on="movie_id")

In [3]:
data.head()

,user_id,movie_id,rating,timestamp,movie_name,tag0,tag1,tag2,tag3,tag4,...,tag8,tag9,tag10,tag11,tag12,tag13,tag14,tag15,tag16,tag17
0,1,1193,5,978300760,One Flew Over the Cuckoo's Nest (1975),0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,1193,5,978298413,One Flew Over the Cuckoo's Nest (1975),0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,12,1193,4,978220179,One Flew Over the Cuckoo's Nest (1975),0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,15,1193,4,978199279,One Flew Over the Cuckoo's Nest (1975),0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,17,1193,5,978158471,One Flew Over the Cuckoo's Nest (1975),0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
# extract feature from our data set
streaming_batch, user_feature, actions, reward_list = feature_extraction(data)

      user_id  movie_id  rating  timestamp                        movie_name  \
1725        1       661       3  978302109  James and the Giant Peach (1996)
1726       23       661       2  978460739  James and the Giant Peach (1996)
1727       49       661       3  977972750  James and the Giant Peach (1996)
1728       53       661       5  977979726  James and the Giant Peach (1996)
1729       57       661       4  977935511  James and the Giant Peach (1996)

      tag0  tag1  tag2  tag3  tag4  ...    tag8  tag9  tag10  tag11  tag12  \
1725   1.0   0.0   1.0   0.0   0.0  ...     0.0   0.0    0.0    1.0    0.0
1726   1.0   0.0   1.0   0.0   0.0  ...     0.0   0.0    0.0    1.0    0.0
1727   1.0   0.0   1.0   0.0   0.0  ...     0.0   0.0    0.0    1.0    0.0
1728   1.0   0.0   1.0   0.0   0.0  ...     0.0   0.0    0.0    1.0    0.0
1729   1.0   0.0   1.0   0.0   0.0  ...     0.0   0.0    0.0    1.0    0.0

      tag13  tag14  tag15  tag16  tag17
1725    0.0    0.0    0.0    0.0    0.0
1726    0.0    0.0    0.0    0.0    0.0
1727    0.0    0.0    0.0    0.0    0.0
1728    0.0    0.0    0.0    0.0    0.0
1729    0.0    0.0    0.0    0.0    0.0

[5 rows x 23 columns]

/Users/01017387/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:48: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

In [5]:
user_feature.head()
#tagは映画ジャンルの分類
#各ユーザごとにtagで特徴量を算出されている

,tag0,tag1,tag2,tag3,tag4,tag5,tag6,tag7,tag8,tag9,tag10,tag11,tag12,tag13,tag14,tag15,tag16,tag17
user_id,,,,,,,,,,,,,,,,,,
1,0.197531,0.024691,0.160494,0.000000,0.111111,0.061728,0.000000,0.185185,0.000000,0.024691,0.012346,0.197531,0.012346,0.00000,0.000000,0.000000,0.000000,0.012346
2,0.000000,0.186957,0.000000,0.008696,0.086957,0.086957,0.004348,0.304348,0.039130,0.052174,0.000000,0.000000,0.052174,0.00000,0.013043,0.013043,0.039130,0.113043
3,0.024691,0.197531,0.012346,0.037037,0.271605,0.024691,0.000000,0.049383,0.000000,0.209877,0.012346,0.024691,0.000000,0.00000,0.074074,0.012346,0.000000,0.049383
4,0.000000,0.434783,0.000000,0.043478,0.000000,0.043478,0.000000,0.130435,0.000000,0.043478,0.000000,0.000000,0.043478,0.00000,0.086957,0.000000,0.086957,0.086957
5,0.006757,0.084459,0.006757,0.030405,0.165541,0.097973,0.003378,0.320946,0.013514,0.013514,0.000000,0.010135,0.057432,0.02027,0.003378,0.023649,0.037162,0.104730

In [6]:
#見られた回数top50のmovieID
print(len(actions))
pd.DataFrame(actions, columns=['movie_id']).head()

50

   movie_id
0      2858
1       260
2      1196
3      1210
4       480

In [7]:
reward_list.head()

        user_id  movie_id  reward
491248     6040       858       1
138498     6040       593       1
12758      6040       919       1
28156      6040       527       1
175478     6040       318       1

In [8]:
#user_id
#時系列に並べる
streaming_batch.to_csv("streaming_batch.csv", sep='\t', index=False)

In [ ]:
#閲覧したジャンルの合計がuser_idごとに正規化されて入っている
user_feature.to_csv("user_feature.csv", sep='\t')
#actionsに見られた回数TOP50が入っている
pd.DataFrame(actions, columns=['movie_id']).to_csv("actions.csv", sep='\t', index=False)
#ユーザ（グループ）、映画ごとに見られたらrewardに１を追加する
reward_list.to_csv("reward_list.csv", sep='\t', index=False)

In [9]:

action_context = movie[movie['movie_id'].isin(actions)]
# action_context.to_csv("action_context.csv", sep='\t', index = False)

In [10]:
#movieIDとtagが入っている
action_context.head()

,movie_id,movie_name,tag0,tag1,tag2,tag3,tag4,tag5,tag6,tag7,tag8,tag9,tag10,tag11,tag12,tag13,tag14,tag15,tag16,tag17
0,1,Toy Story (1995),1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
33,34,Babe (1995),0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
49,50,"Usual Suspects, The (1995)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
108,110,Braveheart (1995),0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
257,260,Star Wars: Episode IV - A New Hope (1977),0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [11]:
actions_id = list(pd.read_csv('actions.csv', sep='\t', header=0, engine='c')['movie_id'])
actions_id
print(len(actions_id))

50

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from striatum.storage import action
from striatum.storage import history
from striatum.storage import model
from striatum.bandit import ucb1
from striatum.bandit import linucb
from striatum.bandit import linthompsamp
from striatum.bandit import exp4p
from striatum.bandit import exp3
from striatum.bandit.bandit import BaseBandit
# from striatum.bandit.bandit import Action
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier

In [6]:
# /Users/01017387/Desktop/jupyter
def get_data():
    streaming_batch = pd.read_csv('streaming_batch.csv', sep='\t', names=['user_id'], engine='c')
    user_feature = pd.read_csv('user_feature.csv', sep='\t', header=0, index_col=0, engine='c')
#     actions_id = list(pd.read_csv('actions.csv', sep='\t', header=0, engine='c')['movie_id'])
    actions = list(pd.read_csv('actions.csv', sep='\t', header=0, engine='c')['movie_id'])
    reward_list = pd.read_csv('reward_list.csv', sep='\t', header=0, engine='c')
    action_context = pd.read_csv('action_context.csv', sep='\t', header=0, engine='c')

#     actions = []
#     for key in actions_id:
# #         action = Action(key)
#         action = BaseBandit(key)
#         actions.append(action)

    return streaming_batch, user_feature, actions, reward_list, action_context

#
def train_expert(action_context):
    logreg = OneVsRestClassifier(LogisticRegression())
    mnb = OneVsRestClassifier(MultinomialNB(), )
    logreg.fit(action_context.iloc[:, 2:], action_context.iloc[:, 1])
    mnb.fit(action_context.iloc[:, 2:], action_context.iloc[:, 1])
    return [logreg, mnb]

def get_advice(context, actions_id, experts):
    advice = {}
    for time in context.keys():
        advice[time] = {}
        for i in range(len(experts)):
            prob = experts[i].predict_proba(context[time])[0]
            advice[time][i] = {}
            for j in range(len(prob)):
                advice[time][i][actions_id[j]] = prob[j]
    return advice

#actions : list of actions should be choosed from
# →list of movieID
#policyが正確に何を意味しているかは微妙にわからん、が、選択の確率を持った何かを出してると思われる
def policy_generation(bandit, actions):
    historystorage = history.MemoryHistoryStorage()
    modelstorage = model.MemoryModelStorage()

#     if bandit == 'Exp4P':
        #選択できるアクション、行動履歴、モデルを入れてる？
        #delta、pminの意味を探る必要ある
    policy = exp4p.Exp4P(actions, historystorage, modelstorage, delta=0.5, p_min=None)

#     elif bandit == 'LinUCB':
# #         policy = linucb.LinUCB(actions, historystorage, modelstorage, 0.3, 20)
#         policy = linucb.LinUCB(historystorage, modelstorage, actions,  0.3, 20)

#     elif bandit == 'LinThompSamp':
#         policy = linthompsamp.LinThompSamp(actions, historystorage, modelstorage,
#                                            d=20, delta=0.61, r=0.01, epsilon=0.71)

#     elif bandit == 'UCB1':
#         policy = ucb1.UCB1(actions, historystorage, modelstorage)

#     elif bandit == 'Exp3':
#         policy = exp3.Exp3(actions, historystorage, modelstorage, gamma=0.2)

#     elif bandit == 'random':
#         policy = 0

    return policy

#選択評価
def policy_evaluation(policy, bandit, streaming_batch, user_feature, reward_list, actions, action_context=None):
    times = len(streaming_batch)
    seq_error = np.zeros(shape=(times, 1))
#     actions_id = [actions[i].action_id for i in range(len(actions))]
    actions_id = [actions[i] for i in range(len(actions))]
    if bandit in ['LinUCB', 'LinThompSamp', 'UCB1', 'Exp3']:
        for t in range(times):
            feature = np.array(user_feature[user_feature.index == streaming_batch.iloc[t, 0]])[0]
            full_context = {}
            for action_id in actions_id:
                full_context[action_id] = feature
            history_id, action = policy.get_action(full_context, 1)
            watched_list = reward_list[reward_list['user_id'] == streaming_batch.iloc[t, 0]]

            if action[0]['action'].action_id not in list(watched_list['movie_id']):
                policy.reward(history_id, {action[0]['action'].action_id: 0.0})
                if t == 0:
                    seq_error[t] = 1.0
                else:
                    seq_error[t] = seq_error[t - 1] + 1.0

            else:
                policy.reward(history_id, {action[0]['action'].action_id: 1.0})
                if t > 0:
                    seq_error[t] = seq_error[t - 1]

    elif bandit == 'Exp4P':
        for t in range(times):
            feature = user_feature[user_feature.index == streaming_batch.iloc[t, 0]]
            experts = train_expert(action_context)
            advice = {}
            for i in range(len(experts)):
                prob = experts[i].predict_proba(feature)[0]
                advice[i] = {}
                for j in range(len(prob)):
                    advice[i][actions_id[j]] = prob[j]
            history_id, action = policy.get_action(advice)
            watched_list = reward_list[reward_list['user_id'] == streaming_batch.iloc[t, 0]]

            if action[0]['action'].action_id not in list(watched_list['movie_id']):
                policy.reward(history_id, {action[0]['action'].action_id: 0.0})
                if t == 0:
                    seq_error[t] = 1.0
                else:
                    seq_error[t] = seq_error[t - 1] + 1.0

            else:
                policy.reward(history_id, {action[0]['action'].action_id: 1.0})
                if t > 0:
                    seq_error[t] = seq_error[t - 1]

    elif bandit == 'random':
        for t in range(times):
            action = actions_id[np.random.randint(0, len(actions)-1)]
            watched_list = reward_list[reward_list['user_id'] == streaming_batch.iloc[t, 0]]

            if action not in list(watched_list['movie_id']):
                if t == 0:
                    seq_error[t] = 1.0
                else:
                    seq_error[t] = seq_error[t - 1] + 1.0

            else:
                if t > 0:
                    seq_error[t] = seq_error[t - 1]

    return seq_error

#regretの計算
def regret_calculation(seq_error):
    t = len(seq_error)
    regret = [x / y for x, y in zip(seq_error, range(1, t + 1))]
    return regret

In [7]:
#1万件で試す
#データの生成
streaming_batch, user_feature, actions, reward_list, action_context = get_data()
streaming_batch_small = streaming_batch.iloc[0:10000]

In [10]:
#ひたすらユーザIDを格納している
#top50の映画以外を見たユーザの
streaming_batch

        user_id
0          6040
1          6040
2          6040
3          6040
4          6040
5          6040
6          6040
7          6040
8          6040
9          6040
10         6040
11         6040
12         6040
13         6040
14         6039
15         6039
16         6039
17         6039
18         6039
19         6039
20         6039
21         6039
22         6039
23         6039
24         6039
25         6038
26         6038
27         6038
28         6038
29         6037
...         ...
109774     5484
109775     5484
109776      736
109777      736
109778      736
109779      736
109780      736
109781      736
109782      736
109783      736
109784      736
109785      736
109786      736
109787     5484
109788     5484
109789     5484
109790     5484
109791     5484
109792     5329
109793     5329
109794     4418
109795     3840
109796     3840
109797     3840
109798     3840
109799     5950
109800     5950
109801     5950
109802     5950
109803     5950

[109804 rows x 1 columns]

In [20]:
# conduct regret analyses
#     experiment_bandit = ['LinUCB', 'LinThompSamp', 'Exp4P', 'UCB1', 'Exp3', 'random']
experiment_bandit = 'Exp4P'
regret = {}
#     col = ['b', 'g', 'r', 'c', 'm', 'y', 'k', 'w']
col = 'b'
i = 0

In [21]:
#     for bandit in experiment_bandit:
policy = policy_generation(experiment_bandit, actions)

In [22]:
seq_error = policy_evaluation(policy, experiment_bandit, streaming_batch_small, user_feature, reward_list,
                              actions, action_context)

AttributeError: 'Exp4P' object has no attribute 'action_ids'

In [ ]:
regret[experiment_bandit] = regret_calculation(seq_error)
plt.plot(range(len(streaming_batch_small)), regret[experiment_bandit], c=col[i], ls='-', label=experiment_bandit)
plt.xlabel('time')
plt.ylabel('regret')
plt.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
axes = plt.gca()
axes.set_ylim([0, 1])
plt.title("Regret Bound with respect to T")
i += 1
plt.show()

In [3]:
#1万件で試す
def main():
    #データの生成
    streaming_batch, user_feature, actions, reward_list, action_context = get_data()
    streaming_batch_small = streaming_batch.iloc[0:10000]

    # conduct regret analyses
#     experiment_bandit = ['LinUCB', 'LinThompSamp', 'Exp4P', 'UCB1', 'Exp3', 'random']
    experiment_bandit = 'Exp4P'
    regret = {}
#     col = ['b', 'g', 'r', 'c', 'm', 'y', 'k', 'w']
    col = 'b'
    i = 0
#     for bandit in experiment_bandit:
    policy = policy_generation(experiment_bandit, actions)
    seq_error = policy_evaluation(policy, experiment_bandit, streaming_batch_small, user_feature, reward_list,
                                  actions, action_context)
    regret[experiment_bandit] = regret_calculation(seq_error)
    plt.plot(range(len(streaming_batch_small)), regret[experiment_bandit], c=col[i], ls='-', label=experiment_bandit)
    plt.xlabel('time')
    plt.ylabel('regret')
    plt.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
    axes = plt.gca()
    axes.set_ylim([0, 1])
    plt.title("Regret Bound with respect to T")
    i += 1
    plt.show()

In [4]:
# #全体バージョンはエラーが出るので一旦やめ
# def main():
#     streaming_batch, user_feature, actions, reward_list, action_context = get_data()
#     streaming_batch_small = streaming_batch.iloc[0:10000]

#     # conduct regret analyses
# #     experiment_bandit = ['LinUCB', 'LinThompSamp', 'Exp4P', 'UCB1', 'Exp3', 'random']
#     experiment_bandit = 'Exp4P'
#     regret = {}
# #     col = ['b', 'g', 'r', 'c', 'm', 'y', 'k', 'w']
#     col = 'b'
#     i = 0
#     for bandit in experiment_bandit:
#         policy = policy_generation(bandit, actions)
#         seq_error = policy_evaluation(policy, bandit, streaming_batch_small, user_feature, reward_list,
#                                       actions, action_context)
#         regret[bandit] = regret_calculation(seq_error)
#         plt.plot(range(len(streaming_batch_small)), regret[bandit], c=col[i], ls='-', label=bandit)
#         plt.xlabel('time')
#         plt.ylabel('regret')
#         plt.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
#         axes = plt.gca()
#         axes.set_ylim([0, 1])
#         plt.title("Regret Bound with respect to T")
#         i += 1
#     plt.show()

In [5]:
if __name__ == '__main__':
    main()

AttributeError: 'Exp4P' object has no attribute 'action_ids'

In [12]:
class exper():
    def print_val(self,a):
        print(a)

#クラスの引数に他のクラス
#defの中身にsuper()をつけた上で、メソッド呼び出し
class subtle(exper):
    def summa(self,b):
        super().print_val(b)
        c = 0
        for i in n:
            c +=i
        return c

In [13]:
n = list(range(4))
e = exper()
j = subtle()
j.summa(n)

[0, 1, 2, 3]

6

6

In [12]:
n

[0, 1, 2, 3]